### ISSUE TITLE
Improve behavior when node is not installed

### ISSUE THREAD

**Issue by jeluard** [boot-cljs-test/node-runner#1]
When `node` is not installed it would be friendlier to print an error once and just skip task execution as opposed to fail each time.

Relates to [boot-cljs-example#14](https://github.com/adzerk-oss/boot-cljs-example/issues/14).

**Comment by jeluard** [comment]
Also the documentation might be improved to mention `node` installation requirement.

**Comment by danielsz** [comment]
Tentative fix in #2

**Comment by myguidingstar-zz** [comment]
Thanks guys. I'm sorry to say node-runner is not good enough. node-runner is now deprecated in favor of [testem-runner](https://github.com/boot-cljs-test/testem-runner). I hope you'll find it useful
